openapi: 3.0.0
info:
  title: Haruki Docs Action
  version: 1.0.0
servers:
  - url: https://docs.googleapis.com/v1
paths:
  /documents/{documentId}:batchUpdate:
    post:
      summary: Google Docsにテキストを追記する
      parameters:
        - name: documentId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                requests:
                  type: array
                  items:
                    type: object
      responses:
        '200':
          description: OK
components: {}
